wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1629451605
    t:
      1:
      - 1
      - 5
      - 9
      4: 3.7.0
      5: 0.12.0
      8:
      - 5
