wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_f1
      5: 1
      6:
      - 1
    - 1: 'mu '
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_f1
      5: 1
      6:
      - 1
    python_version: 3.7.0
    start_time: 1630435134
    t:
      1:
      - 1
      - 5
      - 9
      4: 3.7.0
      5: 0.12.0
      8:
      - 5
